### ISSUE TITLE
Watching folders Recursively?

### ISSUE THREAD

**Issue by matthewpipes** [pulpul-s/watchertoucher#1] opened 2023-11-04 19:45 UTC
Per my understanding this script is able to watch folders recursively. However either something is broken or I'm not doing something correctly. Observe the following two screenshots. The logs show a folder (The Revenant) with a .mkv file inside being created in /mnt/mat-nas/.temp. Good so far. Then it is moved to /mnt/mat-nas/Movies and that is also detected but not touched. My watchertoucher.py file has Movies in the watched libraries and the option to watch folders recursively is enabled. But if I copy paste the revenant.mkv file to /mnt/mat-nas/Movies it is touched. 

Love this tool btw. Any ideas? 

![Screenshot from 2023-11-04 15-36-17](https://github.com/pulpul-s/watchertoucher/assets/64096239/56ad10be-5c60-4045-88ac-e6284e54131a)
![Screenshot from 2023-11-04 15-36-43](https://github.com/pulpul-s/watchertoucher/assets/64096239/18697495-5815-41a1-b8c4-794cec53a5bc)

**Comment by pulpul-s** [comment] 2023-11-06 15:18
I was able to reproduce this, I'll check my code

Edit: found where the bug is. I will upload an updated version later today or tomorrow

**Comment by pulpul-s** [comment] 2023-11-06 17:54
It should be fixed now. Please try the updated version of the script. 

The problem was that it did not think destination folder of move events could be a library folder, since in my initial testing move events were always registered as one remove and one create event. 

Now after testing it for some time I see that watchdog reports them quite arbitarily. Sometimes as move, sometimes as remove+create and sometimes it reports them as move events twice (this could also be something to do how the filesystem handles events). It shouldn't hurt the script though, and only the logging (and maybe touchfile writing, if the timing is right) is done twice. 

Also, you shouldn't change recur from True, since at the moment the logic of the script depends on it.

**Closed as completed** 2023-11-06 18:21 UTC
Labels: bug

**Comment by matthewpipes** [comment] 2023-11-15 20:51
Excellent! I've been using the new script for 2 weeks now and no issues. Much appreciated
